library(e1071)
library(caTools)
library(rpart)
mydata <- read.csv(file = "tripdata.csv", header = TRUE, sep = ",")
subset_mydata <- mydata[,c(1,4,6,9)] 
temp_field <- sample.split(subset_mydata,SplitRatio=0.9)
train <- subset(subset_mydata, temp_field==TRUE)
test <- subset(subset_mydata, temp_field==FALSE)
summary(train)
summary(test)
head(train)
head(test)
fit <- rpart(train$Member.type~.,data=train,method="class")
plot(fit)
text(fit)
pred <- predict(fit, newdata=test[,-4],type=("class"))
mean(pred==test$Member.type)
output <- cbind(test,pred)
View(output)
