/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNI
 * Method:    add
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_TestJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    sub
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_TestJNI_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    mul
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_TestJNI_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    div
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_TestJNI_div
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    fact
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_fact
  (JNIEnv *, jobject, jint);

/*
 * Class:     TestJNI
 * Method:    sin
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_TestJNI_sin
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
